---
- name: Install and configure Keepalived for NGINX Plus HA
  hosts: lb
  become: true

  tasks:
    - name: Install keepalived
      dnf:
        name: keepalived
        state: present
        update_cache: true

    - name: Deploy keepalived.conf from template
      template:
        src: keepalived.conf.j2
        dest: /etc/keepalived/keepalived.conf
        mode: "0644"

    - name: Enable and start keepalived
      systemd:
        name: keepalived
        enabled: true
        state: restarted
